ecobici_pipeline:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: ecobici-availability
      dataset: ecobici_dev_marts
      location: US
      threads: 4
      timeout_seconds: 300

    ci:
      type: bigquery
      method: service-account
      project: ecobici-availability
      dataset: ecobici_dev_marts
      keyfile: /tmp/sa_key.json
      location: US
      threads: 4
      timeout_seconds: 300